### PR TITLE
OTC-1062: manage policy dates when it is payed

### PR DESCRIPTION
**Pull request by lruzicki**
Ticket:
https://openimis.atlassian.net/browse/OTC-1062

Changes:
1. Effective date is equal to payment day of contribution (last payment when a balance became 0)
2. Start date is Enrolment Date if the policy is payed later
3. Expiry date relay on Start date and is postponed as the Start date is

### CODE REVIEW

**Comment by delcroip** [comment]
Can you add the managed  = true too
[itr fails in prod ](https://demo.openimis.org/front/policy/policies)

**Comment by delcroip** [comment]
I know that is a "to be deprecated module" but it is blocking on PSQL

**Comment by lruzicki** [comment]
> I know that is a "to be deprecated module" but it is blocking on PSQL

okay @delcroip , it will be fixed in a moment

**Comment by lruzicki** [comment]
@delcroip This issue is fixed in PR for postgresql script here:  https://github.com/openimis/database_postgresql/pull/9

**Pull request merged**
